[package]
name = "Pyth App"
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies]
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/aptos/contracts", rev = "main" }
amnis = { local = "./interface/amnis" }

[addresses]
oracle = "_"
# On deployment, these should be overridden with --named-addresses using the addresses
# documented at https://docs.pyth.network/documentation/pythnet-price-feeds/aptos#addresses
pyth = "0x7e783b349d3e89cf5931af376ebeadbfab855b3fa239b7ada8f5a92fbea6b387"
deployer = "0xb31e712b26fd295357355f6845e77c888298636609e93bc9b05f0f604049f434"
wormhole = "0x5bc11445584a763c1fa7ed39081f1b920954da14e04b32440cba863d03e19625"



