[package]
name = "amnis"
version = "1.0.0"
authors = []

[addresses]
amnis = "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a"

[dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }

